// Generated by CoffeeScript 1.7.1
(function() {
  var avg, clearCanvas, getCanvas;



  avg = function(a, b) {
    return (a + b) / 2;
  };

  window.avg = avg;


}).call(this);

//# sourceMappingURL=helper.map
