// Generated by CoffeeScript 1.7.1
(function() {
  var angle;

  angle = function(x, y) {
    var a;
    if (x === 0 && y > 0) {
      a = Math.PI / 2;
    }
    if (x === 0 && y < 0) {
      a = -Math.PI / 2;
    }
    if (x > 0) {
      a = Math.atan(y / x);
    }
    if (x < 0) {
      a = Math.atan(-y / -x) + Math.PI;
    }
    if (a < 0) {
      a = a + 2 * Math.PI;
    }
    return a;
  };

  window.findAngle = angle;

}).call(this);

//# sourceMappingURL=mathHelper.map
