// Generated by CoffeeScript 1.7.1
(function() {
  window.Timer = (function() {
    function Timer() {
      this.getStart = (new Date()).getTime();
    }

    Timer.prototype.getTime = function() {
      var cur;
      cur = (new Date).getTime();
      return cur - this.getStart;
    };

    return Timer;

  })();

}).call(this);

//# sourceMappingURL=timer.map
