// Generated by CoffeeScript 1.7.1

/*
 * This file is used to manage connections with the client.
 * @constructor
 */

(function() {
  window.connectionManager = (function() {
    function connectionManager() {
      this.game = null;
      $.ajaxSetup({
        "async": false
      });
      $.getJSON("game/server/maps/europe/europe.json", (function(_this) {
        return function(json) {
          return _this.game = new GameManager(new Europe(json));
        };
      })(this));
    }


    /*
       * Gets information about the map.
     */

    connectionManager.prototype.getMapInfo = function() {
      return this.game.getMapInfo();
    };


    /*
       * Gets information about each player.
     */

    connectionManager.prototype.getPlayerState = function() {
      return this.game.getPlayerState();
    };


    /*
         * Gets information about each region.
     */

    connectionManager.prototype.getRegionStates = function() {
      return this.game.updateState();
    };


    /*
         * Return the clicks that a player made.
     */

    connectionManager.prototype.getSavedClick = function() {
      return this.game.getFirstClickName();
    };


    /*
       * Sends information about the click to the server.
       * @param data Information about the click.
       * @param pName The player that made the click.
     */

    connectionManager.prototype.sendClick = function(data, pName) {
      return this.game.processClick(data, pName);
    };


    /*
       * Adds information about a client player to the server.
       * @param pName The player that is being added.
     */

    connectionManager.prototype.registerPlayer = function(pName) {
      return this.game.registerPlayer(pName);
    };

    connectionManager.prototype.upgradeCommand=function(upCom){
        this.game.upgradeCommand(upCom);
    }

    connectionManager.prototype.researchCommand=function(rName){
        this.game.researchCommand(rName);
    }

    return connectionManager;

  })();

}).call(this);

//# sourceMappingURL=connectionManager.map
