// Generated by CoffeeScript 1.7.1
(function() {
  window.DisplayCache = (function() {
    function DisplayCache() {
      this.updateQueue = {};
      this.regionData = {};
    }

    DisplayCache.prototype.updateReg = function(rName, owner) {
      if (this.regionData[rName] !== owner) {
        this.regionData[rName] = owner;
        return this.updateQueue[rName] = owner;
      }
    };

    DisplayCache.prototype.firstUpdate = function() {
      var k, v, _ref;
      _ref = this.updateQueue;
      for (k in _ref) {
        v = _ref[k];
        return k;
      }
    };

    DisplayCache.prototype.getUpdate = function() {
      var data, key;
      key = this.firstUpdate();
      data = {};
      data["name"] = key;
      data["owner"] = this.updateQueue[key];
      delete this.updateQueue[key];
      return data;
    };

    DisplayCache.prototype.hasUpdates = function() {
      return Object.keys(this.updateQueue).length > 0;
    };

    return DisplayCache;

  })();

}).call(this);

//# sourceMappingURL=displayCache.map
