// Generated by CoffeeScript 1.7.1

/*
 * Starts the client.
 * @param dataConnection The object that will be used to get game state data to render.
 * @param pName The player name.
 */

(function() {
  var startClient;

  startClient = function(dataConnection, pName) {
    var dataCon, disp;
    console.log("Starting client");
    dataCon = dataConnection;
    dataCon.registerPlayer(pName);
    disp = new MapDisplay(dataCon, pName);
    return setInterval(disp.gameLoop, 40);
  };

  window.startClient = startClient;

}).call(this);

//# sourceMappingURL=driver.map
