// Generated by CoffeeScript 1.7.1
(function() {
  var drawArrow;

  drawArrow = function(x1, y1, x2, y2, ctx) {
    var aX, aY, angle;
    aX = x2 - x1;
    aY = y2 - y1;
    angle = findAngle(aX, aY);
    x1 += 15 * Math.cos(angle);
    y1 += 15 * Math.sin(angle);
    x2 -= 15 * Math.cos(angle);
    y2 -= 15 * Math.sin(angle);
    ctx.save();
    ctx.strokeStyle = "Gray";
    ctx.lineWidth = 2;
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2, y2);
    ctx.stroke();
    ctx.restore();
    ctx.save();
    ctx.translate(x2, y2);
    ctx.rotate(angle);
    ctx.translate(-x2, -y2);
    ctx.fillStyle = "Gray";
    ctx.beginPath();
    ctx.moveTo(x2, y2 - 5);
    ctx.lineTo(x2, y2 + 5);
    ctx.lineTo(x2 + 5, y2);
    ctx.closePath();
    ctx.fill();
    return ctx.restore();
  };

  window.drawArrow = drawArrow;

}).call(this);

//# sourceMappingURL=arrow.map
